### PR TITLE
Modify misleading parameter description

### PR DESCRIPTION
**Pull request by maximetinu**
Hi 👋

The description of this parameter made me thought it would be a commit ID, but it's not. It expects a branch name, I realised by reading these GitLab doc: https://docs.gitlab.com/ee/ci/triggers/#pass-cicd-variables-in-the-api-call

This is more of a suggestion but, would not it be better making this more explicit in the parameter description?

### CODE REVIEW

**Comment by louis-z** [comment]
Actually, [the GitLab documentation](https://docs.gitlab.com/ee/api/pipelines.html#create-a-new-pipeline) does describe it as `Reference to commit`. However, you may be right in saying it must be a branch name or a tag, and not a sha1.

**Comment by maximetinu** [comment]
So the description is inherited from them. But yeah I tried with a sha1, because I thought it was expecting that, but it didn't work.

I didn't tried with a tag, but it works well with branches. They also show it with a branch in their examples:

`curl --request POST --header "PRIVATE-TOKEN: <your_access_token>" "https://gitlab.example.com/api/v4/projects/1/pipeline?ref=main"`

**Comment by maximetinu** [comment]
I've submitted a MR to the gitlab docs to propose this same modification, as it wouldn't make much sense for NGitLab to differ from them https://gitlab.com/gitlab-org/gitlab/-/merge_requests/77978 if they change it, I guess we'd be fine changing it as well

**Comment by maximetinu** [comment]
They also believed that the change was correct, made a few grammar corrections and merged it, so I've updated this description to `The branch or tag to run the pipeline on` to reflect their change

**Pull request merged**
