### PR TITLE
Add PublicApiAnalyzers

### LINKED ISSUE #52: Use Microsoft.CodeAnalysis.PublicApiAnalyzers to prevent breaking changes
We should add [Microsoft.CodeAnalysis.PublicApiAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers) to ensure we do not introduce breaking changes to NGitLab and NGitLab.Mock

### PR DESCRIPTION
**Pull request by meziantou**
Fix #52

### CODE REVIEW

**Comment by meziantou** [comment]
@jairbubbles Do you think we should use the "shipped" file. In this project all changes are deployed almost immediately, so all changes should go to the shipped file. But the fixer add new APIs to the unshipped, so it is easier to add them to this file.

**Comment by louis-z** [comment]
> @jairbubbles Do you think we should use the "shipped" file. In this project all changes are deployed almost immediately, so all changes should go to the shipped file. But the fixer add new APIs to the unshipped, so it is easier to add them to this file.

What's the recommended process? To move stuff from Unshipped to Shipped just before tagging?

**Comment by meziantou** [comment]
When you change the public API, new changes should go to the unshipped file. When you release (tag), you should move all changes to shipped.

While we always tag, one of the file seems useless.

**Comment by jairbubbles** [comment]
@meziantou Indeed the Shipped / Unshipped does not make much sense in our case but it's not a big deal.

**Pull request merged**
